-- =====================================================================================================================

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(254) NOT NULL UNIQUE
);

ALTER TABLE users DROP CONSTRAINT IF EXISTS users_name_check;
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_email_check;

ALTER TABLE users ADD CONSTRAINT users_name_check CHECK (TRIM(name) <> '' AND LENGTH(TRIM(name)) >= 2);
ALTER TABLE users ADD CONSTRAINT users_email_check CHECK (TRIM(email) <> '' AND LENGTH(TRIM(email)) >= 6 AND TRIM(email) LIKE '%_@_%._%');

COMMENT ON TABLE users IS 'Содержит информацию о пользователях';
COMMENT ON COLUMN users.id IS 'Уникальный идентификатор пользователя';
COMMENT ON COLUMN users.name IS 'Имя пользователя';
COMMENT ON COLUMN users.email IS 'Адрес электронной почты пользователя';

-- =====================================================================================================================

CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL UNIQUE
);

ALTER TABLE categories DROP CONSTRAINT IF EXISTS categories_name_check;
ALTER TABLE categories ADD CONSTRAINT categories_name_check CHECK (TRIM(name) <> '' AND LENGTH(TRIM(name)) >= 2);

COMMENT ON TABLE categories IS 'Содержит информацию о категориях';
COMMENT ON COLUMN categories.id IS 'Уникальный идентификатор категории';
COMMENT ON COLUMN categories.name IS 'Название категории';

-- =====================================================================================================================

CREATE TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_on TIMESTAMP NOT NULL,
  initiator_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  title VARCHAR(120) NOT NULL,
  annotation VARCHAR(2000) NOT NULL,
  description VARCHAR(7000) NOT NULL,
  event_date TIMESTAMP NOT NULL,
  category_id BIGINT NOT NULL REFERENCES categories (id) ON DELETE CASCADE,
  location VARCHAR(50) NOT NULL,
  published_on TIMESTAMP,
  paid BOOLEAN NOT NULL DEFAULT FALSE,
  participant_limit INTEGER NOT NULL DEFAULT 0,
  request_moderation BOOLEAN NOT NULL DEFAULT TRUE,
  confirmed_requests INTEGER NOT NULL DEFAULT 0,
  state VARCHAR(10) NOT NULL,
  views INTEGER NOT NULL DEFAULT 0
);

ALTER TABLE events DROP CONSTRAINT IF EXISTS events_title_check;
ALTER TABLE events DROP CONSTRAINT IF EXISTS events_annotation_check;
ALTER TABLE events DROP CONSTRAINT IF EXISTS events_description_check;
ALTER TABLE events DROP CONSTRAINT IF EXISTS events_state_check;

ALTER TABLE events ADD CONSTRAINT events_title_check CHECK (TRIM(title) <> '' AND LENGTH(TRIM(title)) >= 3);
ALTER TABLE events ADD CONSTRAINT events_annotation_check CHECK (TRIM(annotation) <> '' AND LENGTH(TRIM(annotation)) >= 20);
ALTER TABLE events ADD CONSTRAINT events_description_check CHECK (TRIM(description) <> '' AND LENGTH(TRIM(description)) >= 20);
ALTER TABLE events ADD CONSTRAINT events_state_check CHECK (state IN ('PENDING', 'PUBLISHED', 'CANCELED'));

COMMENT ON TABLE events IS 'Содержит информацию о событиях';
COMMENT ON COLUMN events.id IS 'Уникальный идентификатор события';
COMMENT ON COLUMN events.created_on IS 'Дата и время создания события';
COMMENT ON COLUMN events.initiator_id IS 'Идентификатор инициатора события';
COMMENT ON COLUMN events.title IS 'Заголовок события';
COMMENT ON COLUMN events.annotation IS 'Краткое описание события';
COMMENT ON COLUMN events.description IS 'Полное описание события';
COMMENT ON COLUMN events.event_date IS 'Дата и время на которые намечено событие';
COMMENT ON COLUMN events.category_id IS 'Идентификатор категории, к которой относится событие';
COMMENT ON COLUMN events.location IS 'Широта и долгота места проведения события';
COMMENT ON COLUMN events.published_on IS 'Дата и время публикации события';
COMMENT ON COLUMN events.paid IS 'Признак, нужно ли оплачивать событие';
COMMENT ON COLUMN events.participant_limit IS 'Ограничение на количество участников';
COMMENT ON COLUMN events.request_moderation IS 'Признак, нужна ли пре-модерация заявок на участие';
COMMENT ON COLUMN events.confirmed_requests IS 'Количество одобренных заявок на участие в данном событии';
COMMENT ON COLUMN events.state IS 'Состояние события';
COMMENT ON COLUMN events.views IS 'Количество просмотров события';