CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(254) NOT NULL UNIQUE
);

ALTER TABLE users DROP CONSTRAINT IF EXISTS users_name_check;
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_email_check;

ALTER TABLE users ADD CONSTRAINT users_name_check CHECK (TRIM(name) <> '' AND LENGTH(TRIM(name)) >= 2);
ALTER TABLE users ADD CONSTRAINT users_email_check CHECK (TRIM(email) <> '' AND LENGTH(TRIM(email)) >= 6 AND TRIM(email) LIKE '%_@__%.__%');

COMMENT ON TABLE users IS 'Содержит информацию о пользователях';
COMMENT ON COLUMN users.id IS 'Уникальный идентификатор пользователя';
COMMENT ON COLUMN users.name IS 'Имя пользователя';
COMMENT ON COLUMN users.email IS 'Адрес электронной почты пользователя';

-- =====================================================================================================================

CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL UNIQUE
);
COMMENT ON TABLE categories IS 'Содержит информацию о категориях';
COMMENT ON COLUMN categories.id IS 'Уникальный идентификатор категории';
COMMENT ON COLUMN categories.name IS 'Название категории';